package com.github.aiderpmsi.pimsdriver.vaadin.utils.aop;

import com.vaadin.event.Action;

public class ActionHandlerEncloser implements Action.Handler {

	/** Autogenerated serialId */
	private static final long serialVersionUID = 8975728886110286674L;

	private final Actions actions;
	
	private final Action filter;
	
	private final ActionHandler handler;
	
	public ActionHandlerEncloser(Action filter, Actions actions, ActionHandler handler) {
		this.filter = filter;
		this.actions = actions;
		this.handler = handler;
	}

	@Override
	public Action[] getActions(Object target, Object sender) {
		if (target != null) {
			return actions.getActions();
		} else {
			return actions.getNoActions();
		}	}

	@Override
	public void handleAction(Action action, Object sender, Object target) {
		if (action.equals(filter)) {
			handler.handleAction(action, sender, target);
		}
	}

	@FunctionalInterface
	public interface ActionHandler {
		public void handleAction(Action action, Object sender, Object target);
	}
	
	public interface Actions {
		public Action[] getActions();
		public Action[] getNoActions();
	}
}
